



















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `myBB`
//     Provider:               `MySql.Data.MySqlClient`
//     Connection String:      `Server=MIASRVRTSIWS1;Port=3306;Database=topsbb;User ID=root;password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `False`



using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PetaPoco;

namespace DataAccess
{

	public partial class mbbDB : Database
	{
		public mbbDB() 
			: base("myBB")
		{
			CommonConstruct();
		}

		public mbbDB(string connectionStringName) 
			: base(connectionStringName)
		{
			CommonConstruct();
		}
		
		partial void CommonConstruct();
		
		public interface IFactory
		{
			mbbDB GetInstance();
		}
		
		public static IFactory Factory { get; set; }
        public static mbbDB GetInstance()
        {
			if (_instance!=null)
				return _instance;
				
			if (Factory!=null)
				return Factory.GetInstance();
			else
				return new mbbDB();
        }

		[ThreadStatic] static mbbDB _instance;
		
		public override void OnBeginTransaction()
		{
			if (_instance==null)
				_instance=this;
		}
		
		public override void OnEndTransaction()
		{
			if (_instance==this)
				_instance=null;
		}
        

		public class Record<T> where T:new()
		{
			public static mbbDB repo { get { return mbbDB.GetInstance(); } }
			public bool IsNew() { return repo.IsNew(this); }
			public object Insert() { return repo.Insert(this); }

			public void Save() { repo.Save(this); }
			public int Update() { return repo.Update(this); }

			public int Update(IEnumerable<string> columns) { return repo.Update(this, columns); }
			public static int Update(string sql, params object[] args) { return repo.Update<T>(sql, args); }
			public static int Update(Sql sql) { return repo.Update<T>(sql); }
			public int Delete() { return repo.Delete(this); }
			public static int Delete(string sql, params object[] args) { return repo.Delete<T>(sql, args); }
			public static int Delete(Sql sql) { return repo.Delete<T>(sql); }
			public static int Delete(object primaryKey) { return repo.Delete<T>(primaryKey); }
			public static bool Exists(object primaryKey) { return repo.Exists<T>(primaryKey); }
			public static bool Exists(string sql, params object[] args) { return repo.Exists<T>(sql, args); }
			public static T SingleOrDefault(object primaryKey) { return repo.SingleOrDefault<T>(primaryKey); }
			public static T SingleOrDefault(string sql, params object[] args) { return repo.SingleOrDefault<T>(sql, args); }
			public static T SingleOrDefault(Sql sql) { return repo.SingleOrDefault<T>(sql); }
			public static T FirstOrDefault(string sql, params object[] args) { return repo.FirstOrDefault<T>(sql, args); }
			public static T FirstOrDefault(Sql sql) { return repo.FirstOrDefault<T>(sql); }
			public static T Single(object primaryKey) { return repo.Single<T>(primaryKey); }
			public static T Single(string sql, params object[] args) { return repo.Single<T>(sql, args); }
			public static T Single(Sql sql) { return repo.Single<T>(sql); }
			public static T First(string sql, params object[] args) { return repo.First<T>(sql, args); }
			public static T First(Sql sql) { return repo.First<T>(sql); }
			public static List<T> Fetch(string sql, params object[] args) { return repo.Fetch<T>(sql, args); }
			public static List<T> Fetch(Sql sql) { return repo.Fetch<T>(sql); }
			public static List<T> Fetch(long page, long itemsPerPage, string sql, params object[] args) { return repo.Fetch<T>(page, itemsPerPage, sql, args); }
			public static List<T> Fetch(long page, long itemsPerPage, Sql sql) { return repo.Fetch<T>(page, itemsPerPage, sql); }
			public static List<T> SkipTake(long skip, long take, string sql, params object[] args) { return repo.SkipTake<T>(skip, take, sql, args); }
			public static List<T> SkipTake(long skip, long take, Sql sql) { return repo.SkipTake<T>(skip, take, sql); }
			public static Page<T> Page(long page, long itemsPerPage, string sql, params object[] args) { return repo.Page<T>(page, itemsPerPage, sql, args); }
			public static Page<T> Page(long page, long itemsPerPage, Sql sql) { return repo.Page<T>(page, itemsPerPage, sql); }
			public static IEnumerable<T> Query(string sql, params object[] args) { return repo.Query<T>(sql, args); }
			public static IEnumerable<T> Query(Sql sql) { return repo.Query<T>(sql); }

		}

	}
	



    
	[TableName("mybb_adminlog")]


	[ExplicitColumns]
    public partial class mybb_adminlog : mbbDB.Record<mybb_adminlog>  
    {



		[Column] public uint uid { get; set; }





		[Column] public string ipaddress { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public string module { get; set; }





		[Column] public string action { get; set; }





		[Column] public string data { get; set; }



	}

    
	[TableName("mybb_adminoptions")]


	[PrimaryKey("uid", autoIncrement=false)]

	[ExplicitColumns]
    public partial class mybb_adminoption : mbbDB.Record<mybb_adminoption>  
    {



		[Column] public int uid { get; set; }





		[Column] public string cpstyle { get; set; }





		[Column] public int codepress { get; set; }





		[Column] public string notes { get; set; }





		[Column] public string permissions { get; set; }





		[Column] public string defaultviews { get; set; }



	}

    
	[TableName("mybb_adminsessions")]


	[ExplicitColumns]
    public partial class mybb_adminsession : mbbDB.Record<mybb_adminsession>  
    {



		[Column] public string sid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public string loginkey { get; set; }





		[Column] public string ip { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public long lastactive { get; set; }





		[Column] public string data { get; set; }



	}

    
	[TableName("mybb_adminviews")]


	[PrimaryKey("vid")]



	[ExplicitColumns]
    public partial class mybb_adminview : mbbDB.Record<mybb_adminview>  
    {



		[Column] public uint vid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public string title { get; set; }





		[Column] public string type { get; set; }





		[Column] public int visibility { get; set; }





		[Column] public string fields { get; set; }





		[Column] public string conditions { get; set; }





		[Column] public string sortby { get; set; }





		[Column] public string sortorder { get; set; }





		[Column] public int perpage { get; set; }





		[Column] public string view_type { get; set; }



	}

    
	[TableName("mybb_announcements")]


	[PrimaryKey("aid")]



	[ExplicitColumns]
    public partial class mybb_announcement : mbbDB.Record<mybb_announcement>  
    {



		[Column] public uint aid { get; set; }





		[Column] public int fid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public string subject { get; set; }





		[Column] public string message { get; set; }





		[Column] public long startdate { get; set; }





		[Column] public long enddate { get; set; }





		[Column] public int allowhtml { get; set; }





		[Column] public int allowmycode { get; set; }





		[Column] public int allowsmilies { get; set; }



	}

    
	[TableName("mybb_attachments")]


	[PrimaryKey("aid")]



	[ExplicitColumns]
    public partial class mybb_attachment : mbbDB.Record<mybb_attachment>  
    {



		[Column] public uint aid { get; set; }





		[Column] public int pid { get; set; }





		[Column] public string posthash { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public string filename { get; set; }





		[Column] public string filetype { get; set; }





		[Column] public int filesize { get; set; }





		[Column] public string attachname { get; set; }





		[Column] public uint downloads { get; set; }





		[Column] public long dateuploaded { get; set; }





		[Column] public int visible { get; set; }





		[Column] public string thumbnail { get; set; }



	}

    
	[TableName("mybb_attachtypes")]


	[PrimaryKey("atid")]



	[ExplicitColumns]
    public partial class mybb_attachtype : mbbDB.Record<mybb_attachtype>  
    {



		[Column] public uint atid { get; set; }





		[Column] public string name { get; set; }





		[Column] public string mimetype { get; set; }





		[Column] public string extension { get; set; }





		[Column] public int maxsize { get; set; }





		[Column] public string icon { get; set; }



	}

    
	[TableName("mybb_awaitingactivation")]


	[PrimaryKey("aid")]



	[ExplicitColumns]
    public partial class mybb_awaitingactivation : mbbDB.Record<mybb_awaitingactivation>  
    {



		[Column] public uint aid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public string code { get; set; }





		[Column] public string type { get; set; }





		[Column] public long oldgroup { get; set; }





		[Column] public string misc { get; set; }



	}

    
	[TableName("mybb_badwords")]


	[PrimaryKey("bid")]



	[ExplicitColumns]
    public partial class mybb_badword : mbbDB.Record<mybb_badword>  
    {



		[Column] public uint bid { get; set; }





		[Column] public string badword { get; set; }





		[Column] public string replacement { get; set; }



	}

    
	[TableName("mybb_banfilters")]


	[PrimaryKey("fid")]



	[ExplicitColumns]
    public partial class mybb_banfilter : mbbDB.Record<mybb_banfilter>  
    {



		[Column] public uint fid { get; set; }





		[Column] public string filter { get; set; }





		[Column] public int type { get; set; }





		[Column] public long lastuse { get; set; }





		[Column] public long dateline { get; set; }



	}

    
	[TableName("mybb_banned")]


	[ExplicitColumns]
    public partial class mybb_banned : mbbDB.Record<mybb_banned>  
    {



		[Column] public uint uid { get; set; }





		[Column] public uint gid { get; set; }





		[Column] public uint oldgroup { get; set; }





		[Column] public string oldadditionalgroups { get; set; }





		[Column] public int olddisplaygroup { get; set; }





		[Column] public uint admin { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public string bantime { get; set; }





		[Column] public long lifted { get; set; }





		[Column] public string reason { get; set; }



	}

    
	[TableName("mybb_calendarpermissions")]


	[ExplicitColumns]
    public partial class mybb_calendarpermission : mbbDB.Record<mybb_calendarpermission>  
    {



		[Column] public uint cid { get; set; }





		[Column] public uint gid { get; set; }





		[Column] public int canviewcalendar { get; set; }





		[Column] public int canaddevents { get; set; }





		[Column] public int canbypasseventmod { get; set; }





		[Column] public int canmoderateevents { get; set; }



	}

    
	[TableName("mybb_calendars")]


	[PrimaryKey("cid")]



	[ExplicitColumns]
    public partial class mybb_calendar : mbbDB.Record<mybb_calendar>  
    {



		[Column] public uint cid { get; set; }





		[Column] public string name { get; set; }





		[Column] public uint disporder { get; set; }





		[Column] public int startofweek { get; set; }





		[Column] public int showbirthdays { get; set; }





		[Column] public int eventlimit { get; set; }





		[Column] public int moderation { get; set; }





		[Column] public int allowhtml { get; set; }





		[Column] public int allowmycode { get; set; }





		[Column] public int allowimgcode { get; set; }





		[Column] public int allowsmilies { get; set; }



	}

    
	[TableName("mybb_captcha")]


	[ExplicitColumns]
    public partial class mybb_captcha : mbbDB.Record<mybb_captcha>  
    {



		[Column] public string imagehash { get; set; }





		[Column] public string imagestring { get; set; }





		[Column] public long dateline { get; set; }



	}

    
	[TableName("mybb_datacache")]


	[PrimaryKey("title", autoIncrement=false)]

	[ExplicitColumns]
    public partial class mybb_datacache : mbbDB.Record<mybb_datacache>  
    {



		[Column] public string title { get; set; }





		[Column] public string cache { get; set; }



	}

    
	[TableName("mybb_events")]


	[PrimaryKey("eid")]



	[ExplicitColumns]
    public partial class mybb_event : mbbDB.Record<mybb_event>  
    {



		[Column] public uint eid { get; set; }





		[Column] public uint cid { get; set; }





		[Column] public string name { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public string description { get; set; }





		[Column] public int visible { get; set; }





		[Column("private")] public int @private { get; set; }





		[Column] public uint dateline { get; set; }





		[Column] public uint starttime { get; set; }





		[Column] public uint endtime { get; set; }





		[Column] public string timezone { get; set; }





		[Column] public int ignoretimezone { get; set; }





		[Column] public int usingtime { get; set; }





		[Column] public string repeats { get; set; }



	}

    
	[TableName("mybb_forumpermissions")]


	[PrimaryKey("pid")]



	[ExplicitColumns]
    public partial class mybb_forumpermission : mbbDB.Record<mybb_forumpermission>  
    {



		[Column] public uint pid { get; set; }





		[Column] public uint fid { get; set; }





		[Column] public uint gid { get; set; }





		[Column] public int canview { get; set; }





		[Column] public int canviewthreads { get; set; }





		[Column] public int candlattachments { get; set; }





		[Column] public int canpostthreads { get; set; }





		[Column] public int canpostreplys { get; set; }





		[Column] public int canpostattachments { get; set; }





		[Column] public int canratethreads { get; set; }





		[Column] public int caneditposts { get; set; }





		[Column] public int candeleteposts { get; set; }





		[Column] public int candeletethreads { get; set; }





		[Column] public int caneditattachments { get; set; }





		[Column] public int canpostpolls { get; set; }





		[Column] public int canvotepolls { get; set; }





		[Column] public int cansearch { get; set; }



	}

    
	[TableName("mybb_forums")]


	[PrimaryKey("fid")]



	[ExplicitColumns]
    public partial class mybb_forum : mbbDB.Record<mybb_forum>  
    {



		[Column] public ushort fid { get; set; }





		[Column] public string name { get; set; }





		[Column] public string description { get; set; }





		[Column] public string linkto { get; set; }





		[Column] public string type { get; set; }





		[Column] public ushort pid { get; set; }





		[Column] public string parentlist { get; set; }





		[Column] public ushort disporder { get; set; }





		[Column] public int active { get; set; }





		[Column] public int open { get; set; }





		[Column] public uint threads { get; set; }





		[Column] public uint posts { get; set; }





		[Column] public uint lastpost { get; set; }





		[Column] public string lastposter { get; set; }





		[Column] public uint lastposteruid { get; set; }





		[Column] public int lastposttid { get; set; }





		[Column] public string lastpostsubject { get; set; }





		[Column] public int allowhtml { get; set; }





		[Column] public int allowmycode { get; set; }





		[Column] public int allowsmilies { get; set; }





		[Column] public int allowimgcode { get; set; }





		[Column] public int allowpicons { get; set; }





		[Column] public int allowtratings { get; set; }





		[Column] public int status { get; set; }





		[Column] public int usepostcounts { get; set; }





		[Column] public string password { get; set; }





		[Column] public int showinjump { get; set; }





		[Column] public int modposts { get; set; }





		[Column] public int modthreads { get; set; }





		[Column] public int mod_edit_posts { get; set; }





		[Column] public int modattachments { get; set; }





		[Column] public ushort style { get; set; }





		[Column] public int overridestyle { get; set; }





		[Column] public short rulestype { get; set; }





		[Column] public string rulestitle { get; set; }





		[Column] public string rules { get; set; }





		[Column] public uint unapprovedthreads { get; set; }





		[Column] public uint unapprovedposts { get; set; }





		[Column] public ushort defaultdatecut { get; set; }





		[Column] public string defaultsortby { get; set; }





		[Column] public string defaultsortorder { get; set; }



	}

    
	[TableName("mybb_forumsubscriptions")]


	[PrimaryKey("fsid")]



	[ExplicitColumns]
    public partial class mybb_forumsubscription : mbbDB.Record<mybb_forumsubscription>  
    {



		[Column] public uint fsid { get; set; }





		[Column] public ushort fid { get; set; }





		[Column] public uint uid { get; set; }



	}

    
	[TableName("mybb_groupleaders")]


	[PrimaryKey("lid")]



	[ExplicitColumns]
    public partial class mybb_groupleader : mbbDB.Record<mybb_groupleader>  
    {



		[Column] public ushort lid { get; set; }





		[Column] public ushort gid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public int canmanagemembers { get; set; }





		[Column] public int canmanagerequests { get; set; }



	}

    
	[TableName("mybb_helpdocs")]


	[PrimaryKey("hid")]



	[ExplicitColumns]
    public partial class mybb_helpdoc : mbbDB.Record<mybb_helpdoc>  
    {



		[Column] public ushort hid { get; set; }





		[Column] public ushort sid { get; set; }





		[Column] public string name { get; set; }





		[Column] public string description { get; set; }





		[Column] public string document { get; set; }





		[Column] public int usetranslation { get; set; }





		[Column] public int enabled { get; set; }





		[Column] public ushort disporder { get; set; }



	}

    
	[TableName("mybb_helpsections")]


	[PrimaryKey("sid")]



	[ExplicitColumns]
    public partial class mybb_helpsection : mbbDB.Record<mybb_helpsection>  
    {



		[Column] public ushort sid { get; set; }





		[Column] public string name { get; set; }





		[Column] public string description { get; set; }





		[Column] public int usetranslation { get; set; }





		[Column] public int enabled { get; set; }





		[Column] public ushort disporder { get; set; }



	}

    
	[TableName("mybb_icons")]


	[PrimaryKey("iid")]



	[ExplicitColumns]
    public partial class mybb_icon : mbbDB.Record<mybb_icon>  
    {



		[Column] public ushort iid { get; set; }





		[Column] public string name { get; set; }





		[Column] public string path { get; set; }



	}

    
	[TableName("mybb_joinrequests")]


	[PrimaryKey("rid")]



	[ExplicitColumns]
    public partial class mybb_joinrequest : mbbDB.Record<mybb_joinrequest>  
    {



		[Column] public uint rid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public ushort gid { get; set; }





		[Column] public string reason { get; set; }





		[Column] public long dateline { get; set; }



	}

    
	[TableName("mybb_mailerrors")]


	[PrimaryKey("eid")]



	[ExplicitColumns]
    public partial class mybb_mailerror : mbbDB.Record<mybb_mailerror>  
    {



		[Column] public uint eid { get; set; }





		[Column] public string subject { get; set; }





		[Column] public string message { get; set; }





		[Column] public string toaddress { get; set; }





		[Column] public string fromaddress { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public string error { get; set; }





		[Column] public string smtperror { get; set; }





		[Column] public int smtpcode { get; set; }



	}

    
	[TableName("mybb_maillogs")]


	[PrimaryKey("mid")]



	[ExplicitColumns]
    public partial class mybb_maillog : mbbDB.Record<mybb_maillog>  
    {



		[Column] public uint mid { get; set; }





		[Column] public string subject { get; set; }





		[Column] public string message { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public uint fromuid { get; set; }





		[Column] public string fromemail { get; set; }





		[Column] public long touid { get; set; }





		[Column] public string toemail { get; set; }





		[Column] public uint tid { get; set; }





		[Column] public string ipaddress { get; set; }



	}

    
	[TableName("mybb_mailqueue")]


	[PrimaryKey("mid")]



	[ExplicitColumns]
    public partial class mybb_mailqueue : mbbDB.Record<mybb_mailqueue>  
    {



		[Column] public uint mid { get; set; }





		[Column] public string mailto { get; set; }





		[Column] public string mailfrom { get; set; }





		[Column] public string subject { get; set; }





		[Column] public string message { get; set; }





		[Column] public string headers { get; set; }



	}

    
	[TableName("mybb_massemails")]


	[PrimaryKey("mid")]



	[ExplicitColumns]
    public partial class mybb_massemail : mbbDB.Record<mybb_massemail>  
    {



		[Column] public uint mid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public string subject { get; set; }





		[Column] public string message { get; set; }





		[Column] public string htmlmessage { get; set; }





		[Column] public sbyte type { get; set; }





		[Column] public sbyte format { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public long senddate { get; set; }





		[Column] public sbyte status { get; set; }





		[Column] public uint sentcount { get; set; }





		[Column] public uint totalcount { get; set; }





		[Column] public string conditions { get; set; }





		[Column] public short perpage { get; set; }



	}

    
	[TableName("mybb_moderatorlog")]


	[ExplicitColumns]
    public partial class mybb_moderatorlog : mbbDB.Record<mybb_moderatorlog>  
    {



		[Column] public uint uid { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public ushort fid { get; set; }





		[Column] public uint tid { get; set; }





		[Column] public uint pid { get; set; }





		[Column] public string action { get; set; }





		[Column] public string data { get; set; }





		[Column] public string ipaddress { get; set; }



	}

    
	[TableName("mybb_moderators")]


	[PrimaryKey("mid")]



	[ExplicitColumns]
    public partial class mybb_moderator : mbbDB.Record<mybb_moderator>  
    {



		[Column] public ushort mid { get; set; }





		[Column] public ushort fid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public int caneditposts { get; set; }





		[Column] public int candeleteposts { get; set; }





		[Column] public int canviewips { get; set; }





		[Column] public int canopenclosethreads { get; set; }





		[Column] public int canmanagethreads { get; set; }





		[Column] public int canmovetononmodforum { get; set; }



	}

    
	[TableName("mybb_modtools")]


	[PrimaryKey("tid")]



	[ExplicitColumns]
    public partial class mybb_modtool : mbbDB.Record<mybb_modtool>  
    {



		[Column] public ushort tid { get; set; }





		[Column] public string name { get; set; }





		[Column] public string description { get; set; }





		[Column] public string forums { get; set; }





		[Column] public string type { get; set; }





		[Column] public string postoptions { get; set; }





		[Column] public string threadoptions { get; set; }



	}

    
	[TableName("mybb_mycode")]


	[PrimaryKey("cid")]



	[ExplicitColumns]
    public partial class mybb_mycode : mbbDB.Record<mybb_mycode>  
    {



		[Column] public uint cid { get; set; }





		[Column] public string title { get; set; }





		[Column] public string description { get; set; }





		[Column] public string regex { get; set; }





		[Column] public string replacement { get; set; }





		[Column] public int active { get; set; }





		[Column] public ushort parseorder { get; set; }



	}

    
	[TableName("mybb_polls")]


	[PrimaryKey("pid")]



	[ExplicitColumns]
    public partial class mybb_poll : mbbDB.Record<mybb_poll>  
    {



		[Column] public uint pid { get; set; }





		[Column] public uint tid { get; set; }





		[Column] public string question { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public string options { get; set; }





		[Column] public string votes { get; set; }





		[Column] public ushort numoptions { get; set; }





		[Column] public ushort numvotes { get; set; }





		[Column] public long timeout { get; set; }





		[Column] public int closed { get; set; }





		[Column] public int multiple { get; set; }





		[Column("public")] public int @public { get; set; }



	}

    
	[TableName("mybb_pollvotes")]


	[PrimaryKey("vid")]



	[ExplicitColumns]
    public partial class mybb_pollvote : mbbDB.Record<mybb_pollvote>  
    {



		[Column] public uint vid { get; set; }





		[Column] public uint pid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public ushort voteoption { get; set; }





		[Column] public long dateline { get; set; }



	}

    
	[TableName("mybb_posts")]


	[PrimaryKey("pid")]



	[ExplicitColumns]
    public partial class mybb_post : mbbDB.Record<mybb_post>  
    {



		[Column] public uint pid { get; set; }





		[Column] public uint tid { get; set; }





		[Column] public uint replyto { get; set; }





		[Column] public ushort fid { get; set; }





		[Column] public string subject { get; set; }





		[Column] public ushort icon { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public string username { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public string message { get; set; }





		[Column] public string ipaddress { get; set; }





		[Column] public int longipaddress { get; set; }





		[Column] public int includesig { get; set; }





		[Column] public int smilieoff { get; set; }





		[Column] public uint edituid { get; set; }





		[Column] public int edittime { get; set; }





		[Column] public int visible { get; set; }





		[Column] public string posthash { get; set; }



	}

    
	[TableName("mybb_privatemessages")]


	[PrimaryKey("pmid")]



	[ExplicitColumns]
    public partial class mybb_privatemessage : mbbDB.Record<mybb_privatemessage>  
    {



		[Column] public uint pmid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public uint toid { get; set; }





		[Column] public uint fromid { get; set; }





		[Column] public string recipients { get; set; }





		[Column] public ushort folder { get; set; }





		[Column] public string subject { get; set; }





		[Column] public ushort icon { get; set; }





		[Column] public string message { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public long deletetime { get; set; }





		[Column] public int status { get; set; }





		[Column] public long statustime { get; set; }





		[Column] public int includesig { get; set; }





		[Column] public int smilieoff { get; set; }





		[Column] public int receipt { get; set; }





		[Column] public long readtime { get; set; }



	}

    
	[TableName("mybb_profilefields")]


	[PrimaryKey("fid")]



	[ExplicitColumns]
    public partial class mybb_profilefield : mbbDB.Record<mybb_profilefield>  
    {



		[Column] public ushort fid { get; set; }





		[Column] public string name { get; set; }





		[Column] public string description { get; set; }





		[Column] public ushort disporder { get; set; }





		[Column] public string type { get; set; }





		[Column] public ushort length { get; set; }





		[Column] public ushort maxlength { get; set; }





		[Column] public int required { get; set; }





		[Column] public int editable { get; set; }





		[Column] public int hidden { get; set; }



	}

    
	[TableName("mybb_promotionlogs")]


	[PrimaryKey("plid")]



	[ExplicitColumns]
    public partial class mybb_promotionlog : mbbDB.Record<mybb_promotionlog>  
    {



		[Column] public uint plid { get; set; }





		[Column] public uint pid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public string oldusergroup { get; set; }





		[Column] public ushort newusergroup { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public string type { get; set; }



	}

    
	[TableName("mybb_promotions")]


	[PrimaryKey("pid")]



	[ExplicitColumns]
    public partial class mybb_promotion : mbbDB.Record<mybb_promotion>  
    {



		[Column] public uint pid { get; set; }





		[Column] public string title { get; set; }





		[Column] public string description { get; set; }





		[Column] public sbyte enabled { get; set; }





		[Column] public sbyte logging { get; set; }





		[Column] public int posts { get; set; }





		[Column] public string posttype { get; set; }





		[Column] public int registered { get; set; }





		[Column] public string registeredtype { get; set; }





		[Column] public int reputations { get; set; }





		[Column] public string reputationtype { get; set; }





		[Column] public string requirements { get; set; }





		[Column] public string originalusergroup { get; set; }





		[Column] public ushort newusergroup { get; set; }





		[Column] public string usergrouptype { get; set; }



	}

    
	[TableName("mybb_reportedposts")]


	[PrimaryKey("rid")]



	[ExplicitColumns]
    public partial class mybb_reportedpost : mbbDB.Record<mybb_reportedpost>  
    {



		[Column] public uint rid { get; set; }





		[Column] public uint pid { get; set; }





		[Column] public uint tid { get; set; }





		[Column] public uint fid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public int reportstatus { get; set; }





		[Column] public string reason { get; set; }





		[Column] public long dateline { get; set; }



	}

    
	[TableName("mybb_reputation")]


	[PrimaryKey("rid")]



	[ExplicitColumns]
    public partial class mybb_reputation : mbbDB.Record<mybb_reputation>  
    {



		[Column] public uint rid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public uint adduid { get; set; }





		[Column] public long reputation { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public string comments { get; set; }



	}

    
	[TableName("mybb_searchlog")]


	[PrimaryKey("sid", autoIncrement=false)]

	[ExplicitColumns]
    public partial class mybb_searchlog : mbbDB.Record<mybb_searchlog>  
    {



		[Column] public string sid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public string ipaddress { get; set; }





		[Column] public string threads { get; set; }





		[Column] public string posts { get; set; }





		[Column] public string searchtype { get; set; }





		[Column] public string resulttype { get; set; }





		[Column] public string querycache { get; set; }





		[Column] public string keywords { get; set; }



	}

    
	[TableName("mybb_sessions")]


	[PrimaryKey("sid", autoIncrement=false)]

	[ExplicitColumns]
    public partial class mybb_session : mbbDB.Record<mybb_session>  
    {



		[Column] public string sid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public string ip { get; set; }





		[Column] public long time { get; set; }





		[Column] public string location { get; set; }





		[Column] public string useragent { get; set; }





		[Column] public int anonymous { get; set; }





		[Column] public int nopermission { get; set; }





		[Column] public int location1 { get; set; }





		[Column] public int location2 { get; set; }



	}

    
	[TableName("mybb_settinggroups")]


	[PrimaryKey("gid")]



	[ExplicitColumns]
    public partial class mybb_settinggroup : mbbDB.Record<mybb_settinggroup>  
    {



		[Column] public ushort gid { get; set; }





		[Column] public string name { get; set; }





		[Column] public string title { get; set; }





		[Column] public string description { get; set; }





		[Column] public ushort disporder { get; set; }





		[Column] public string isdefault { get; set; }



	}

    
	[TableName("mybb_settings")]


	[PrimaryKey("sid")]



	[ExplicitColumns]
    public partial class mybb_setting : mbbDB.Record<mybb_setting>  
    {



		[Column] public ushort sid { get; set; }





		[Column] public string name { get; set; }





		[Column] public string title { get; set; }





		[Column] public string description { get; set; }





		[Column] public string optionscode { get; set; }





		[Column] public string value { get; set; }





		[Column] public ushort disporder { get; set; }





		[Column] public ushort gid { get; set; }





		[Column] public int isdefault { get; set; }



	}

    
	[TableName("mybb_smilies")]


	[PrimaryKey("sid")]



	[ExplicitColumns]
    public partial class mybb_smily : mbbDB.Record<mybb_smily>  
    {



		[Column] public ushort sid { get; set; }





		[Column] public string name { get; set; }





		[Column] public string find { get; set; }





		[Column] public string image { get; set; }





		[Column] public ushort disporder { get; set; }





		[Column] public int showclickable { get; set; }



	}

    
	[TableName("mybb_spiders")]


	[PrimaryKey("sid")]



	[ExplicitColumns]
    public partial class mybb_spider : mbbDB.Record<mybb_spider>  
    {



		[Column] public uint sid { get; set; }





		[Column] public string name { get; set; }





		[Column] public uint theme { get; set; }





		[Column] public string language { get; set; }





		[Column] public uint usergroup { get; set; }





		[Column] public string useragent { get; set; }





		[Column] public long lastvisit { get; set; }



	}

    
	[TableName("mybb_stats")]


	[PrimaryKey("dateline", autoIncrement=false)]

	[ExplicitColumns]
    public partial class mybb_stat : mbbDB.Record<mybb_stat>  
    {



		[Column] public long dateline { get; set; }





		[Column] public uint numusers { get; set; }





		[Column] public uint numthreads { get; set; }





		[Column] public uint numposts { get; set; }



	}

    
	[TableName("mybb_tasklog")]


	[PrimaryKey("lid")]



	[ExplicitColumns]
    public partial class mybb_tasklog : mbbDB.Record<mybb_tasklog>  
    {



		[Column] public uint lid { get; set; }





		[Column] public uint tid { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public string data { get; set; }



	}

    
	[TableName("mybb_tasks")]


	[PrimaryKey("tid")]



	[ExplicitColumns]
    public partial class mybb_task : mbbDB.Record<mybb_task>  
    {



		[Column] public uint tid { get; set; }





		[Column] public string title { get; set; }





		[Column] public string description { get; set; }





		[Column] public string file { get; set; }





		[Column] public string minute { get; set; }





		[Column] public string hour { get; set; }





		[Column] public string day { get; set; }





		[Column] public string month { get; set; }





		[Column] public string weekday { get; set; }





		[Column] public long nextrun { get; set; }





		[Column] public long lastrun { get; set; }





		[Column] public int enabled { get; set; }





		[Column] public int logging { get; set; }





		[Column] public long locked { get; set; }



	}

    
	[TableName("mybb_templategroups")]


	[PrimaryKey("gid")]



	[ExplicitColumns]
    public partial class mybb_templategroup : mbbDB.Record<mybb_templategroup>  
    {



		[Column] public uint gid { get; set; }





		[Column] public string prefix { get; set; }





		[Column] public string title { get; set; }



	}

    
	[TableName("mybb_templates")]


	[PrimaryKey("tid")]



	[ExplicitColumns]
    public partial class mybb_template : mbbDB.Record<mybb_template>  
    {



		[Column] public uint tid { get; set; }





		[Column] public string title { get; set; }





		[Column] public string template { get; set; }





		[Column] public int sid { get; set; }





		[Column] public uint version { get; set; }





		[Column] public string status { get; set; }





		[Column] public int dateline { get; set; }



	}

    
	[TableName("mybb_templatesets")]


	[PrimaryKey("sid")]



	[ExplicitColumns]
    public partial class mybb_templateset : mbbDB.Record<mybb_templateset>  
    {



		[Column] public ushort sid { get; set; }





		[Column] public string title { get; set; }



	}

    
	[TableName("mybb_themes")]


	[PrimaryKey("tid")]



	[ExplicitColumns]
    public partial class mybb_theme : mbbDB.Record<mybb_theme>  
    {



		[Column] public ushort tid { get; set; }





		[Column] public string name { get; set; }





		[Column] public ushort pid { get; set; }





		[Column] public short def { get; set; }





		[Column] public string properties { get; set; }





		[Column] public string stylesheets { get; set; }





		[Column] public string allowedgroups { get; set; }



	}

    
	[TableName("mybb_themestylesheets")]


	[PrimaryKey("sid")]



	[ExplicitColumns]
    public partial class mybb_themestylesheet : mbbDB.Record<mybb_themestylesheet>  
    {



		[Column] public uint sid { get; set; }





		[Column] public string name { get; set; }





		[Column] public uint tid { get; set; }





		[Column] public string attachedto { get; set; }





		[Column] public string stylesheet { get; set; }





		[Column] public string cachefile { get; set; }





		[Column] public long lastmodified { get; set; }



	}

    
	[TableName("mybb_threadratings")]


	[PrimaryKey("rid")]



	[ExplicitColumns]
    public partial class mybb_threadrating : mbbDB.Record<mybb_threadrating>  
    {



		[Column] public uint rid { get; set; }





		[Column] public uint tid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public ushort rating { get; set; }





		[Column] public string ipaddress { get; set; }



	}

    
	[TableName("mybb_threads")]


	[PrimaryKey("tid")]



	[ExplicitColumns]
    public partial class mybb_thread : mbbDB.Record<mybb_thread>  
    {



		[Column] public uint tid { get; set; }





		[Column] public ushort fid { get; set; }





		[Column] public string subject { get; set; }





		[Column] public ushort icon { get; set; }





		[Column] public uint poll { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public string username { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public uint firstpost { get; set; }





		[Column] public long lastpost { get; set; }





		[Column] public string lastposter { get; set; }





		[Column] public uint lastposteruid { get; set; }





		[Column] public int views { get; set; }





		[Column] public int replies { get; set; }





		[Column] public string closed { get; set; }





		[Column] public int sticky { get; set; }





		[Column] public ushort numratings { get; set; }





		[Column] public ushort totalratings { get; set; }





		[Column] public string notes { get; set; }





		[Column] public int visible { get; set; }





		[Column] public uint unapprovedposts { get; set; }





		[Column] public uint attachmentcount { get; set; }





		[Column] public uint deletetime { get; set; }



	}

    
	[TableName("mybb_threadsubscriptions")]


	[PrimaryKey("sid")]



	[ExplicitColumns]
    public partial class mybb_threadsubscription : mbbDB.Record<mybb_threadsubscription>  
    {



		[Column] public uint sid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public uint tid { get; set; }





		[Column] public int notification { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public string subscriptionkey { get; set; }



	}

    
	[TableName("mybb_threadviews")]


	[ExplicitColumns]
    public partial class mybb_threadview : mbbDB.Record<mybb_threadview>  
    {



		[Column] public uint tid { get; set; }



	}

    
	[TableName("mybb_upgrade_data")]


	[PrimaryKey("title", autoIncrement=false)]

	[ExplicitColumns]
    public partial class mybb_upgrade_datum : mbbDB.Record<mybb_upgrade_datum>  
    {



		[Column] public string title { get; set; }





		[Column] public string contents { get; set; }



	}

    
	[TableName("mybb_userfields")]


	[PrimaryKey("ufid", autoIncrement=false)]

	[ExplicitColumns]
    public partial class mybb_userfield : mbbDB.Record<mybb_userfield>  
    {



		[Column] public uint ufid { get; set; }





		[Column] public string fid1 { get; set; }





		[Column] public string fid2 { get; set; }





		[Column] public string fid3 { get; set; }



	}

    
	[TableName("mybb_usergroups")]


	[PrimaryKey("gid")]



	[ExplicitColumns]
    public partial class mybb_usergroup : mbbDB.Record<mybb_usergroup>  
    {



		[Column] public ushort gid { get; set; }





		[Column] public short type { get; set; }





		[Column] public string title { get; set; }





		[Column] public string description { get; set; }





		[Column] public string namestyle { get; set; }





		[Column] public string usertitle { get; set; }





		[Column] public short stars { get; set; }





		[Column] public string starimage { get; set; }





		[Column] public string image { get; set; }





		[Column] public ushort disporder { get; set; }





		[Column] public int isbannedgroup { get; set; }





		[Column] public int canview { get; set; }





		[Column] public int canviewthreads { get; set; }





		[Column] public int canviewprofiles { get; set; }





		[Column] public int candlattachments { get; set; }





		[Column] public int canpostthreads { get; set; }





		[Column] public int canpostreplys { get; set; }





		[Column] public int canpostattachments { get; set; }





		[Column] public int canratethreads { get; set; }





		[Column] public int caneditposts { get; set; }





		[Column] public int candeleteposts { get; set; }





		[Column] public int candeletethreads { get; set; }





		[Column] public int caneditattachments { get; set; }





		[Column] public int canpostpolls { get; set; }





		[Column] public int canvotepolls { get; set; }





		[Column] public int canusepms { get; set; }





		[Column] public int cansendpms { get; set; }





		[Column] public int cantrackpms { get; set; }





		[Column] public int candenypmreceipts { get; set; }





		[Column] public int pmquota { get; set; }





		[Column] public int maxpmrecipients { get; set; }





		[Column] public int cansendemail { get; set; }





		[Column] public int maxemails { get; set; }





		[Column] public int canviewmemberlist { get; set; }





		[Column] public int canviewcalendar { get; set; }





		[Column] public int canaddevents { get; set; }





		[Column] public int canbypasseventmod { get; set; }





		[Column] public int canmoderateevents { get; set; }





		[Column] public int canviewonline { get; set; }





		[Column] public int canviewwolinvis { get; set; }





		[Column] public int canviewonlineips { get; set; }





		[Column] public int cancp { get; set; }





		[Column] public int issupermod { get; set; }





		[Column] public int cansearch { get; set; }





		[Column] public int canusercp { get; set; }





		[Column] public int canuploadavatars { get; set; }





		[Column] public int canratemembers { get; set; }





		[Column] public int canchangename { get; set; }





		[Column] public int showforumteam { get; set; }





		[Column] public int usereputationsystem { get; set; }





		[Column] public int cangivereputations { get; set; }





		[Column] public long reputationpower { get; set; }





		[Column] public long maxreputationsday { get; set; }





		[Column] public int candisplaygroup { get; set; }





		[Column] public long attachquota { get; set; }





		[Column] public int cancustomtitle { get; set; }





		[Column] public int canwarnusers { get; set; }





		[Column] public int canreceivewarnings { get; set; }





		[Column] public int maxwarningsday { get; set; }





		[Column] public int canmodcp { get; set; }



	}

    
	[TableName("mybb_users")]


	[PrimaryKey("uid")]



	[ExplicitColumns]
    public partial class mybb_user : mbbDB.Record<mybb_user>  
    {



		[Column] public uint uid { get; set; }





		[Column] public string username { get; set; }





		[Column] public string password { get; set; }





		[Column] public string salt { get; set; }





		[Column] public string loginkey { get; set; }





		[Column] public string email { get; set; }





		[Column] public int postnum { get; set; }





		[Column] public string avatar { get; set; }





		[Column] public string avatardimensions { get; set; }





		[Column] public string avatartype { get; set; }





		[Column] public ushort usergroup { get; set; }





		[Column] public string additionalgroups { get; set; }





		[Column] public ushort displaygroup { get; set; }





		[Column] public string usertitle { get; set; }





		[Column] public long regdate { get; set; }





		[Column] public long lastactive { get; set; }





		[Column] public long lastvisit { get; set; }





		[Column] public long lastpost { get; set; }





		[Column] public string website { get; set; }





		[Column] public string icq { get; set; }





		[Column] public string aim { get; set; }





		[Column] public string yahoo { get; set; }





		[Column] public string msn { get; set; }





		[Column] public string birthday { get; set; }





		[Column] public string birthdayprivacy { get; set; }





		[Column] public string signature { get; set; }





		[Column] public int allownotices { get; set; }





		[Column] public int hideemail { get; set; }





		[Column] public int subscriptionmethod { get; set; }





		[Column] public int invisible { get; set; }





		[Column] public int receivepms { get; set; }





		[Column] public int pmnotice { get; set; }





		[Column] public int pmnotify { get; set; }





		[Column] public int remember { get; set; }





		[Column] public string threadmode { get; set; }





		[Column] public int showsigs { get; set; }





		[Column] public int showavatars { get; set; }





		[Column] public int showquickreply { get; set; }





		[Column] public int showredirect { get; set; }





		[Column] public short ppp { get; set; }





		[Column] public short tpp { get; set; }





		[Column] public short daysprune { get; set; }





		[Column] public string dateformat { get; set; }





		[Column] public string timeformat { get; set; }





		[Column] public string timezone { get; set; }





		[Column] public int dst { get; set; }





		[Column] public int dstcorrection { get; set; }





		[Column] public string buddylist { get; set; }





		[Column] public string ignorelist { get; set; }





		[Column] public ushort style { get; set; }





		[Column] public int away { get; set; }





		[Column] public uint awaydate { get; set; }





		[Column] public string returndate { get; set; }





		[Column] public string awayreason { get; set; }





		[Column] public string pmfolders { get; set; }





		[Column] public string notepad { get; set; }





		[Column] public uint referrer { get; set; }





		[Column] public long reputation { get; set; }





		[Column] public string regip { get; set; }





		[Column] public string lastip { get; set; }





		[Column] public int longlastip { get; set; }





		[Column] public int longregip { get; set; }





		[Column] public string language { get; set; }





		[Column] public long timeonline { get; set; }





		[Column] public int showcodebuttons { get; set; }





		[Column] public int totalpms { get; set; }





		[Column] public int unreadpms { get; set; }





		[Column] public int warningpoints { get; set; }





		[Column] public int moderateposts { get; set; }





		[Column] public long moderationtime { get; set; }





		[Column] public int suspendposting { get; set; }





		[Column] public long suspensiontime { get; set; }





		[Column] public int coppauser { get; set; }





		[Column] public int classicpostbit { get; set; }





		[Column] public sbyte loginattempts { get; set; }





		[Column] public long failedlogin { get; set; }



	}

    
	[TableName("mybb_usertitles")]


	[PrimaryKey("utid")]



	[ExplicitColumns]
    public partial class mybb_usertitle : mbbDB.Record<mybb_usertitle>  
    {



		[Column] public ushort utid { get; set; }





		[Column] public uint posts { get; set; }





		[Column] public string title { get; set; }





		[Column] public short stars { get; set; }





		[Column] public string starimage { get; set; }



	}

    
	[TableName("mybb_warninglevels")]


	[PrimaryKey("lid")]



	[ExplicitColumns]
    public partial class mybb_warninglevel : mbbDB.Record<mybb_warninglevel>  
    {



		[Column] public uint lid { get; set; }





		[Column] public int percentage { get; set; }





		[Column] public string action { get; set; }



	}

    
	[TableName("mybb_warnings")]


	[PrimaryKey("wid")]



	[ExplicitColumns]
    public partial class mybb_warning : mbbDB.Record<mybb_warning>  
    {



		[Column] public uint wid { get; set; }





		[Column] public uint uid { get; set; }





		[Column] public uint tid { get; set; }





		[Column] public uint pid { get; set; }





		[Column] public string title { get; set; }





		[Column] public uint points { get; set; }





		[Column] public long dateline { get; set; }





		[Column] public uint issuedby { get; set; }





		[Column] public long expires { get; set; }





		[Column] public int expired { get; set; }





		[Column] public long daterevoked { get; set; }





		[Column] public uint revokedby { get; set; }





		[Column] public string revokereason { get; set; }





		[Column] public string notes { get; set; }



	}

    
	[TableName("mybb_warningtypes")]


	[PrimaryKey("tid")]



	[ExplicitColumns]
    public partial class mybb_warningtype : mbbDB.Record<mybb_warningtype>  
    {



		[Column] public uint tid { get; set; }





		[Column] public string title { get; set; }





		[Column] public uint points { get; set; }





		[Column] public long expirationtime { get; set; }



	}


}



